// go run mksyscall_solaris.go -tags solaris,sparc64 syscall_solaris.go syscall_solaris_sparc64.go
// Code generated by the command above; see README.md. DO NOT EDIT.

// +build solaris,sparc64

package unix

/*
#include <sys/stdint.h>
#include <sys/inttypes.h>
#include <stddef.h>
int pipe(uintptr_t);
int getsockname(int, uintptr_t, uintptr_t);
int getcwd(uintptr_t, size_t);
int getgroups(int, uintptr_t);
int setgroups(int, uintptr_t);
int wait4(int, uintptr_t, int, uintptr_t);
int gethostname(uintptr_t, size_t);
int utimes(uintptr_t, uintptr_t);
int utimensat(int, uintptr_t, uintptr_t, int);
int fcntl(uintptr_t, int, uintptr_t);
int futimesat(int, uintptr_t, uintptr_t);
int accept(int, uintptr_t, uintptr_t);
int __xnet_recvmsg(int, uintptr_t, int);
int __xnet_sendmsg(int, uintptr_t, int);
int acct(uintptr_t);
unsigned long long __makedev(int, int, int);
int __major(int, unsigned long long);
int __minor(int, unsigned long long);
int ioctl(int, int, uintptr_t);
int poll(uintptr_t, int, int);
int access(uintptr_t, unsigned int);
int adjtime(uintptr_t, uintptr_t);
int chdir(uintptr_t);
int chmod(uintptr_t, unsigned int);
int chown(uintptr_t, int, int);
int chroot(uintptr_t);
int close(int);
int creat(uintptr_t, unsigned int);
int dup(int);
int dup2(int, int);
void exit(int);
int faccessat(int, uintptr_t, unsigned int, int);
int fchdir(int);
int fchmod(int, unsigned int);
int fchmodat(int, uintptr_t, unsigned int, int);
int fchown(int, int, int);
int fchownat(int, uintptr_t, int, int, int);
int fdatasync(int);
int flock(int, int);
int fpathconf(int, int);
int fstat(int, uintptr_t);
int fstatat(int, uintptr_t, uintptr_t, int);
int fstatvfs(int, uintptr_t);
int getdents(int, uintptr_t, size_t, uintptr_t);
int getgid();
int getpid();
int getpgid(int);
int getpgrp();
int geteuid();
int getegid();
int getppid();
int getpriority(int, int);
int getrlimit(int, uintptr_t);
int getrusage(int, uintptr_t);
int gettimeofday(uintptr_t);
int getuid();
int kill(int, int);
int lchown(uintptr_t, int, int);
int link(uintptr_t, uintptr_t);
int __xnet_llisten(int, int);
int lstat(uintptr_t, uintptr_t);
int madvise(uintptr_t, size_t, int);
int mkdir(uintptr_t, unsigned int);
int mkdirat(int, uintptr_t, unsigned int);
int mkfifo(uintptr_t, unsigned int);
int mkfifoat(int, uintptr_t, unsigned int);
int mknod(uintptr_t, unsigned int, int);
int mknodat(int, uintptr_t, unsigned int, int);
int mlock(uintptr_t, size_t);
int mlockall(int);
int mprotect(uintptr_t, size_t, int);
int msync(uintptr_t, size_t, int);
int munlock(uintptr_t, size_t);
int munlockall();
int nanosleep(uintptr_t, uintptr_t);
int open(uintptr_t, int, unsigned int);
int openat(int, uintptr_t, int, unsigned int);
int pathconf(uintptr_t, int);
int pause();
int pread(int, uintptr_t, size_t, long long);
int pwrite(int, uintptr_t, size_t, long long);
int read(int, uintptr_t, size_t);
int readlink(uintptr_t, uintptr_t, size_t);
int rename(uintptr_t, uintptr_t);
int renameat(int, uintptr_t, int, uintptr_t);
int rmdir(uintptr_t);
long long lseek(int, long long, int);
#define c_select select
int select(int, uintptr_t, uintptr_t, uintptr_t, uintptr_t);
int setegid(int);
int seteuid(int);
int setgid(int);
int sethostname(uintptr_t, size_t);
int setpgid(int, int);
int setpriority(int, int, int);
int setregid(int, int);
int setreuid(int, int);
int setrlimit(int, uintptr_t);
int setsid();
int setuid(int);
int shutdown(int, int);
int stat(uintptr_t, uintptr_t);
int statvfs(uintptr_t, uintptr_t);
int symlink(uintptr_t, uintptr_t);
int sync();
uintptr_t times(uintptr_t);
int truncate(uintptr_t, long long);
int fsync(int);
int ftruncate(int, long long);
int umask(int);
int uname(uintptr_t);
int umount(uintptr_t, int);
int unlink(uintptr_t);
int unlinkat(int, uintptr_t, int);
int ustat(int, uintptr_t);
int utime(uintptr_t, uintptr_t);
int __xnet_bind(int, uintptr_t, uintptr_t);
int __xnet_connect(int, uintptr_t, uintptr_t);
uintptr_t mmap(uintptr_t, uintptr_t, int, int, int, long long);
int munmap(uintptr_t, uintptr_t);
int sendfile(int, int, uintptr_t, int);
int __xnet_sendto(int, uintptr_t, size_t, int, uintptr_t, uintptr_t);
int __xnet_socket(int, int, int);
int __xnet_socketpair(int, int, int, uintptr_t);
int write(int, uintptr_t, size_t);
int __xnet_getsockopt(int, int, int, uintptr_t, uintptr_t);
int getpeername(int, uintptr_t, uintptr_t);
int setsockopt(int, int, int, uintptr_t, uintptr_t);
int recvfrom(int, uintptr_t, size_t, int, uintptr_t, uintptr_t);

*/
import "C"
import (
	"syscall"
	"unsafe"
)




// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func pipe(p *[2]_C_int) (n int, err error) {
	r0, e1 := callpipe(uintptr(unsafe.Pointer(p)))
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func getsockname(fd int, rsa *RawSockaddrAny, addrlen *_Socklen) (err error) {
	_, e1 := callgetsockname(fd, uintptr(unsafe.Pointer(rsa)), uintptr(unsafe.Pointer(addrlen)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getcwd(buf []byte) (n int, err error) {
	var _p0 *byte
	if len(buf) > 0 {
		_p0 = &buf[0]
	}
	r0, e1 := callgetcwd(uintptr(unsafe.Pointer(_p0)), len(buf))
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func getgroups(ngid int, gid *_Gid_t) (n int, err error) {
	r0, e1 := callgetgroups(ngid, uintptr(unsafe.Pointer(gid)))
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func setgroups(ngid int, gid *_Gid_t) (err error) {
	_, e1 := callsetgroups(ngid, uintptr(unsafe.Pointer(gid)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func wait4(pid int32, statusp *_C_int, options int, rusage *Rusage) (wpid int32, err error) {
	r0, e1 := callwait4(pid, uintptr(unsafe.Pointer(statusp)), options, uintptr(unsafe.Pointer(rusage)))
	wpid = int32(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func gethostname(buf []byte) (n int, err error) {
	var _p0 *byte
	if len(buf) > 0 {
		_p0 = &buf[0]
	}
	r0, e1 := callgethostname(uintptr(unsafe.Pointer(_p0)), len(buf))
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func utimes(path string, times *[2]Timeval) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callutimes(uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(times)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func utimensat(fd int, path string, times *[2]Timespec, flag int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callutimensat(fd, uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(times)), flag)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func fcntl(fd int, cmd int, arg int) (val int, err error) {
	r0, e1 := callfcntl(uintptr(fd), cmd, uintptr(arg))
	val = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func futimesat(fildes int, path *byte, times *[2]Timeval) (err error) {
	_, e1 := callfutimesat(fildes, uintptr(unsafe.Pointer(path)), uintptr(unsafe.Pointer(times)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func accept(s int, rsa *RawSockaddrAny, addrlen *_Socklen) (fd int, err error) {
	r0, e1 := callaccept(s, uintptr(unsafe.Pointer(rsa)), uintptr(unsafe.Pointer(addrlen)))
	fd = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func recvmsg(s int, msg *Msghdr, flags int) (n int, err error) {
	r0, e1 := call__xnet_recvmsg(s, uintptr(unsafe.Pointer(msg)), flags)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func sendmsg(s int, msg *Msghdr, flags int) (n int, err error) {
	r0, e1 := call__xnet_sendmsg(s, uintptr(unsafe.Pointer(msg)), flags)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func acct(path *byte) (err error) {
	_, e1 := callacct(uintptr(unsafe.Pointer(path)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func __makedev(version int, major uint, minor uint) (val uint64) {
	r0, _ := call__makedev(version, int(major), int(minor))
	val = uint64(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func __major(version int, dev uint64) (val uint) {
	r0, _ := call__major(version, dev)
	val = uint(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func __minor(version int, dev uint64) (val uint) {
	r0, _ := call__minor(version, dev)
	val = uint(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func ioctl(fd int, req uint, arg uintptr) (err error) {
	_, e1 := callioctl(fd, int(req), arg)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func poll(fds *PollFd, nfds int, timeout int) (n int, err error) {
	r0, e1 := callpoll(uintptr(unsafe.Pointer(fds)), nfds, timeout)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Access(path string, mode uint32) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callaccess(uintptr(unsafe.Pointer(_p0)), mode)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Adjtime(delta *Timeval, olddelta *Timeval) (err error) {
	_, e1 := calladjtime(uintptr(unsafe.Pointer(delta)), uintptr(unsafe.Pointer(olddelta)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Chdir(path string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callchdir(uintptr(unsafe.Pointer(_p0)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Chmod(path string, mode uint32) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callchmod(uintptr(unsafe.Pointer(_p0)), mode)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Chown(path string, uid int, gid int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callchown(uintptr(unsafe.Pointer(_p0)), uid, gid)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Chroot(path string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callchroot(uintptr(unsafe.Pointer(_p0)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Close(fd int) (err error) {
	_, e1 := callclose(fd)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Creat(path string, mode uint32) (fd int, err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	r0, e1 := callcreat(uintptr(unsafe.Pointer(_p0)), mode)
	fd = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Dup(fd int) (nfd int, err error) {
	r0, e1 := calldup(fd)
	nfd = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Dup2(oldfd int, newfd int) (err error) {
	_, e1 := calldup2(oldfd, newfd)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Exit(code int) {
	callexit(code)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Faccessat(dirfd int, path string, mode uint32, flags int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callfaccessat(dirfd, uintptr(unsafe.Pointer(_p0)), mode, flags)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fchdir(fd int) (err error) {
	_, e1 := callfchdir(fd)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fchmod(fd int, mode uint32) (err error) {
	_, e1 := callfchmod(fd, mode)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fchmodat(dirfd int, path string, mode uint32, flags int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callfchmodat(dirfd, uintptr(unsafe.Pointer(_p0)), mode, flags)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fchown(fd int, uid int, gid int) (err error) {
	_, e1 := callfchown(fd, uid, gid)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fchownat(dirfd int, path string, uid int, gid int, flags int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callfchownat(dirfd, uintptr(unsafe.Pointer(_p0)), uid, gid, flags)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fdatasync(fd int) (err error) {
	_, e1 := callfdatasync(fd)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Flock(fd int, how int) (err error) {
	_, e1 := callflock(fd, how)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fpathconf(fd int, name int) (val int, err error) {
	r0, e1 := callfpathconf(fd, name)
	val = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fstat(fd int, stat *Stat_t) (err error) {
	_, e1 := callfstat(fd, uintptr(unsafe.Pointer(stat)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fstatat(fd int, path string, stat *Stat_t, flags int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callfstatat(fd, uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(stat)), flags)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fstatvfs(fd int, vfsstat *Statvfs_t) (err error) {
	_, e1 := callfstatvfs(fd, uintptr(unsafe.Pointer(vfsstat)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getdents(fd int, buf []byte, basep *uintptr) (n int, err error) {
	var _p0 *byte
	if len(buf) > 0 {
		_p0 = &buf[0]
	}
	r0, e1 := callgetdents(fd, uintptr(unsafe.Pointer(_p0)), len(buf), uintptr(unsafe.Pointer(basep)))
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getgid() (gid int) {
	r0, _ := callgetgid()
	gid = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getpid() (pid int) {
	r0, _ := callgetpid()
	pid = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getpgid(pid int) (pgid int, err error) {
	r0, e1 := callgetpgid(pid)
	pgid = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getpgrp() (pgid int, err error) {
	r0, e1 := callgetpgrp()
	pgid = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Geteuid() (euid int) {
	r0, _ := callgeteuid()
	euid = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getegid() (egid int) {
	r0, _ := callgetegid()
	egid = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getppid() (ppid int) {
	r0, _ := callgetppid()
	ppid = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getpriority(which int, who int) (n int, err error) {
	r0, e1 := callgetpriority(which, who)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getrlimit(which int, lim *Rlimit) (err error) {
	_, e1 := callgetrlimit(which, uintptr(unsafe.Pointer(lim)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getrusage(who int, rusage *Rusage) (err error) {
	_, e1 := callgetrusage(who, uintptr(unsafe.Pointer(rusage)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Gettimeofday(tv *Timeval) (err error) {
	_, e1 := callgettimeofday(uintptr(unsafe.Pointer(tv)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Getuid() (uid int) {
	r0, _ := callgetuid()
	uid = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Kill(pid int, signum syscall.Signal) (err error) {
	_, e1 := callkill(pid, int(signum))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Lchown(path string, uid int, gid int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := calllchown(uintptr(unsafe.Pointer(_p0)), uid, gid)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Link(path string, link string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	var _p1 *byte
	_p1, err = BytePtrFromString(link)
	if err != nil {
		return
	}
	_, e1 := calllink(uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(_p1)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Listen(s int, backlog int) (err error) {
	_, e1 := call__xnet_llisten(s, backlog)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Lstat(path string, stat *Stat_t) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := calllstat(uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(stat)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Madvise(b []byte, advice int) (err error) {
	var _p0 *byte
	if len(b) > 0 {
		_p0 = &b[0]
	}
	_, e1 := callmadvise(uintptr(unsafe.Pointer(_p0)), len(b), advice)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Mkdir(path string, mode uint32) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callmkdir(uintptr(unsafe.Pointer(_p0)), mode)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Mkdirat(dirfd int, path string, mode uint32) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callmkdirat(dirfd, uintptr(unsafe.Pointer(_p0)), mode)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Mkfifo(path string, mode uint32) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callmkfifo(uintptr(unsafe.Pointer(_p0)), mode)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Mkfifoat(dirfd int, path string, mode uint32) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callmkfifoat(dirfd, uintptr(unsafe.Pointer(_p0)), mode)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Mknod(path string, mode uint32, dev int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callmknod(uintptr(unsafe.Pointer(_p0)), mode, dev)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Mknodat(dirfd int, path string, mode uint32, dev int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callmknodat(dirfd, uintptr(unsafe.Pointer(_p0)), mode, dev)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Mlock(b []byte) (err error) {
	var _p0 *byte
	if len(b) > 0 {
		_p0 = &b[0]
	}
	_, e1 := callmlock(uintptr(unsafe.Pointer(_p0)), len(b))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Mlockall(flags int) (err error) {
	_, e1 := callmlockall(flags)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Mprotect(b []byte, prot int) (err error) {
	var _p0 *byte
	if len(b) > 0 {
		_p0 = &b[0]
	}
	_, e1 := callmprotect(uintptr(unsafe.Pointer(_p0)), len(b), prot)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Msync(b []byte, flags int) (err error) {
	var _p0 *byte
	if len(b) > 0 {
		_p0 = &b[0]
	}
	_, e1 := callmsync(uintptr(unsafe.Pointer(_p0)), len(b), flags)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Munlock(b []byte) (err error) {
	var _p0 *byte
	if len(b) > 0 {
		_p0 = &b[0]
	}
	_, e1 := callmunlock(uintptr(unsafe.Pointer(_p0)), len(b))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Munlockall() (err error) {
	_, e1 := callmunlockall()
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Nanosleep(time *Timespec, leftover *Timespec) (err error) {
	_, e1 := callnanosleep(uintptr(unsafe.Pointer(time)), uintptr(unsafe.Pointer(leftover)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Open(path string, mode int, perm uint32) (fd int, err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	r0, e1 := callopen(uintptr(unsafe.Pointer(_p0)), mode, perm)
	fd = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Openat(dirfd int, path string, flags int, mode uint32) (fd int, err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	r0, e1 := callopenat(dirfd, uintptr(unsafe.Pointer(_p0)), flags, mode)
	fd = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Pathconf(path string, name int) (val int, err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	r0, e1 := callpathconf(uintptr(unsafe.Pointer(_p0)), name)
	val = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Pause() (err error) {
	_, e1 := callpause()
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Pread(fd int, p []byte, offset int64) (n int, err error) {
	var _p0 *byte
	if len(p) > 0 {
		_p0 = &p[0]
	}
	r0, e1 := callpread(fd, uintptr(unsafe.Pointer(_p0)), len(p), offset)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Pwrite(fd int, p []byte, offset int64) (n int, err error) {
	var _p0 *byte
	if len(p) > 0 {
		_p0 = &p[0]
	}
	r0, e1 := callpwrite(fd, uintptr(unsafe.Pointer(_p0)), len(p), offset)
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func read(fd int, p []byte) (n int, err error) {
	var _p0 *byte
	if len(p) > 0 {
		_p0 = &p[0]
	}
	r0, e1 := callread(fd, uintptr(unsafe.Pointer(_p0)), len(p))
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Readlink(path string, buf []byte) (n int, err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	var _p1 *byte
	if len(buf) > 0 {
		_p1 = &buf[0]
	}
	r0, e1 := callreadlink(uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(_p1)), len(buf))
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Rename(from string, to string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(from)
	if err != nil {
		return
	}
	var _p1 *byte
	_p1, err = BytePtrFromString(to)
	if err != nil {
		return
	}
	_, e1 := callrename(uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(_p1)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Renameat(olddirfd int, oldpath string, newdirfd int, newpath string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(oldpath)
	if err != nil {
		return
	}
	var _p1 *byte
	_p1, err = BytePtrFromString(newpath)
	if err != nil {
		return
	}
	_, e1 := callrenameat(olddirfd, uintptr(unsafe.Pointer(_p0)), newdirfd, uintptr(unsafe.Pointer(_p1)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Rmdir(path string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callrmdir(uintptr(unsafe.Pointer(_p0)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Seek(fd int, offset int64, whence int) (newoffset int64, err error) {
	r0, e1 := calllseek(fd, offset, whence)
	newoffset = int64(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Select(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timeval) (n int, err error) {
	r0, e1 := callselect(nfd, uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(w)), uintptr(unsafe.Pointer(e)), uintptr(unsafe.Pointer(timeout)))
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setegid(egid int) (err error) {
	_, e1 := callsetegid(egid)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Seteuid(euid int) (err error) {
	_, e1 := callseteuid(euid)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setgid(gid int) (err error) {
	_, e1 := callsetgid(gid)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Sethostname(p []byte) (err error) {
	var _p0 *byte
	if len(p) > 0 {
		_p0 = &p[0]
	}
	_, e1 := callsethostname(uintptr(unsafe.Pointer(_p0)), len(p))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setpgid(pid int, pgid int) (err error) {
	_, e1 := callsetpgid(pid, pgid)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setpriority(which int, who int, prio int) (err error) {
	_, e1 := callsetpriority(which, who, prio)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setregid(rgid int, egid int) (err error) {
	_, e1 := callsetregid(rgid, egid)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setreuid(ruid int, euid int) (err error) {
	_, e1 := callsetreuid(ruid, euid)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setrlimit(which int, lim *Rlimit) (err error) {
	_, e1 := callsetrlimit(which, uintptr(unsafe.Pointer(lim)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setsid() (pid int, err error) {
	r0, e1 := callsetsid()
	pid = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Setuid(uid int) (err error) {
	_, e1 := callsetuid(uid)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Shutdown(s int, how int) (err error) {
	_, e1 := callshutdown(s, how)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Stat(path string, stat *Stat_t) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callstat(uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(stat)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Statvfs(path string, vfsstat *Statvfs_t) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callstatvfs(uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(vfsstat)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Symlink(path string, link string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	var _p1 *byte
	_p1, err = BytePtrFromString(link)
	if err != nil {
		return
	}
	_, e1 := callsymlink(uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(_p1)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Sync() (err error) {
	_, e1 := callsync()
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Times(tms *Tms) (ticks uintptr, err error) {
	r0, e1 := calltimes(uintptr(unsafe.Pointer(tms)))
	ticks = uintptr(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Truncate(path string, length int64) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := calltruncate(uintptr(unsafe.Pointer(_p0)), length)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Fsync(fd int) (err error) {
	_, e1 := callfsync(fd)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Ftruncate(fd int, length int64) (err error) {
	_, e1 := callftruncate(fd, length)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Umask(mask int) (oldmask int) {
	r0, _ := callumask(mask)
	oldmask = int(r0)
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Uname(buf *Utsname) (err error) {
	_, e1 := calluname(uintptr(unsafe.Pointer(buf)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Unmount(target string, flags int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(target)
	if err != nil {
		return
	}
	_, e1 := callumount(uintptr(unsafe.Pointer(_p0)), flags)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Unlink(path string) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callunlink(uintptr(unsafe.Pointer(_p0)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Unlinkat(dirfd int, path string, flags int) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callunlinkat(dirfd, uintptr(unsafe.Pointer(_p0)), flags)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Ustat(dev int, ubuf *Ustat_t) (err error) {
	_, e1 := callustat(dev, uintptr(unsafe.Pointer(ubuf)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func Utime(path string, buf *Utimbuf) (err error) {
	var _p0 *byte
	_p0, err = BytePtrFromString(path)
	if err != nil {
		return
	}
	_, e1 := callutime(uintptr(unsafe.Pointer(_p0)), uintptr(unsafe.Pointer(buf)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func bind(s int, addr unsafe.Pointer, addrlen _Socklen) (err error) {
	_, e1 := call__xnet_bind(s, uintptr(addr), uintptr(addrlen))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func connect(s int, addr unsafe.Pointer, addrlen _Socklen) (err error) {
	_, e1 := call__xnet_connect(s, uintptr(addr), uintptr(addrlen))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func mmap(addr uintptr, length uintptr, prot int, flag int, fd int, pos int64) (ret uintptr, err error) {
	r0, e1 := callmmap(addr, length, prot, flag, fd, pos)
	ret = uintptr(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func munmap(addr uintptr, length uintptr) (err error) {
	_, e1 := callmunmap(addr, length)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func sendfile(outfd int, infd int, offset *int64, count int) (written int, err error) {
	r0, e1 := callsendfile(outfd, infd, uintptr(unsafe.Pointer(offset)), count)
	written = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func sendto(s int, buf []byte, flags int, to unsafe.Pointer, addrlen _Socklen) (err error) {
	var _p0 *byte
	if len(buf) > 0 {
		_p0 = &buf[0]
	}
	_, e1 := call__xnet_sendto(s, uintptr(unsafe.Pointer(_p0)), len(buf), flags, uintptr(to), uintptr(addrlen))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func socket(domain int, typ int, proto int) (fd int, err error) {
	r0, e1 := call__xnet_socket(domain, typ, proto)
	fd = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func socketpair(domain int, typ int, proto int, fd *[2]int32) (err error) {
	_, e1 := call__xnet_socketpair(domain, typ, proto, uintptr(unsafe.Pointer(fd)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func write(fd int, p []byte) (n int, err error) {
	var _p0 *byte
	if len(p) > 0 {
		_p0 = &p[0]
	}
	r0, e1 := callwrite(fd, uintptr(unsafe.Pointer(_p0)), len(p))
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func getsockopt(s int, level int, name int, val unsafe.Pointer, vallen *_Socklen) (err error) {
	_, e1 := call__xnet_getsockopt(s, level, name, uintptr(val), uintptr(unsafe.Pointer(vallen)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func getpeername(fd int, rsa *RawSockaddrAny, addrlen *_Socklen) (err error) {
	_, e1 := callgetpeername(fd, uintptr(unsafe.Pointer(rsa)), uintptr(unsafe.Pointer(addrlen)))
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func setsockopt(s int, level int, name int, val unsafe.Pointer, vallen uintptr) (err error) {
	_, e1 := callsetsockopt(s, level, name, uintptr(val), vallen)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT


func recvfrom(fd int, p []byte, flags int, from *RawSockaddrAny, fromlen *_Socklen) (n int, err error) {
	var _p0 *byte
	if len(p) > 0 {
		_p0 = &p[0]
	}
	r0, e1 := callrecvfrom(fd, uintptr(unsafe.Pointer(_p0)), len(p), flags, uintptr(unsafe.Pointer(from)), uintptr(unsafe.Pointer(fromlen)))
	n = int(r0)
	if e1 != 0 {
		err = errnoErr(e1)
	}
	return
}






// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callpipe(p uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.pipe(C.uintptr_t(p)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetsockname(fd int, rsa uintptr, addrlen uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getsockname(C.int(fd), C.uintptr_t(rsa), C.uintptr_t(addrlen)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetcwd(_p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getcwd(C.uintptr_t(_p0), C.size_t(_lenp0)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetgroups(ngid int, gid uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getgroups(C.int(ngid), C.uintptr_t(gid)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetgroups(ngid int, gid uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.setgroups(C.int(ngid), C.uintptr_t(gid)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callwait4(pid int32, statusp uintptr, options int, rusage uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.wait4(C.int(pid), C.uintptr_t(statusp), C.int(options), C.uintptr_t(rusage)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgethostname(_p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.gethostname(C.uintptr_t(_p0), C.size_t(_lenp0)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callutimes(_p0 uintptr, times uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.utimes(C.uintptr_t(_p0), C.uintptr_t(times)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callutimensat(fd int, _p0 uintptr, times uintptr, flag int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.utimensat(C.int(fd), C.uintptr_t(_p0), C.uintptr_t(times), C.int(flag)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfcntl(fd uintptr, cmd int, arg uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.fcntl(C.uintptr_t(fd), C.int(cmd), C.uintptr_t(arg)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfutimesat(fildes int, path uintptr, times uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.futimesat(C.int(fildes), C.uintptr_t(path), C.uintptr_t(times)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callaccept(s int, rsa uintptr, addrlen uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.accept(C.int(s), C.uintptr_t(rsa), C.uintptr_t(addrlen)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_recvmsg(s int, msg uintptr, flags int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.__xnet_recvmsg(C.int(s), C.uintptr_t(msg), C.int(flags)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_sendmsg(s int, msg uintptr, flags int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.__xnet_sendmsg(C.int(s), C.uintptr_t(msg), C.int(flags)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callacct(path uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.acct(C.uintptr_t(path)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__makedev(version int, major int, minor int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.__makedev(C.int(version), C.int(major), C.int(minor)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__major(version int, dev uint64) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.__major(C.int(version), C.ulonglong(dev)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__minor(version int, dev uint64) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.__minor(C.int(version), C.ulonglong(dev)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callioctl(fd int, req int, arg uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.ioctl(C.int(fd), C.int(req), C.uintptr_t(arg)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callpoll(fds uintptr, nfds int, timeout int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.poll(C.uintptr_t(fds), C.int(nfds), C.int(timeout)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callaccess(_p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.access(C.uintptr_t(_p0), C.uint(mode)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calladjtime(delta uintptr, olddelta uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.adjtime(C.uintptr_t(delta), C.uintptr_t(olddelta)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callchdir(_p0 uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.chdir(C.uintptr_t(_p0)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callchmod(_p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.chmod(C.uintptr_t(_p0), C.uint(mode)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callchown(_p0 uintptr, uid int, gid int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.chown(C.uintptr_t(_p0), C.int(uid), C.int(gid)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callchroot(_p0 uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.chroot(C.uintptr_t(_p0)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callclose(fd int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.close(C.int(fd)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callcreat(_p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.creat(C.uintptr_t(_p0), C.uint(mode)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calldup(fd int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.dup(C.int(fd)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calldup2(oldfd int, newfd int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.dup2(C.int(oldfd), C.int(newfd)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callexit(code int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.exit(C.int(code)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfaccessat(dirfd int, _p0 uintptr, mode uint32, flags int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.faccessat(C.int(dirfd), C.uintptr_t(_p0), C.uint(mode), C.int(flags)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfchdir(fd int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.fchdir(C.int(fd)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfchmod(fd int, mode uint32) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.fchmod(C.int(fd), C.uint(mode)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfchmodat(dirfd int, _p0 uintptr, mode uint32, flags int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.fchmodat(C.int(dirfd), C.uintptr_t(_p0), C.uint(mode), C.int(flags)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfchown(fd int, uid int, gid int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.fchown(C.int(fd), C.int(uid), C.int(gid)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfchownat(dirfd int, _p0 uintptr, uid int, gid int, flags int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.fchownat(C.int(dirfd), C.uintptr_t(_p0), C.int(uid), C.int(gid), C.int(flags)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfdatasync(fd int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.fdatasync(C.int(fd)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callflock(fd int, how int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.flock(C.int(fd), C.int(how)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfpathconf(fd int, name int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.fpathconf(C.int(fd), C.int(name)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfstat(fd int, stat uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.fstat(C.int(fd), C.uintptr_t(stat)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfstatat(fd int, _p0 uintptr, stat uintptr, flags int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.fstatat(C.int(fd), C.uintptr_t(_p0), C.uintptr_t(stat), C.int(flags)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfstatvfs(fd int, vfsstat uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.fstatvfs(C.int(fd), C.uintptr_t(vfsstat)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetdents(fd int, _p0 uintptr, _lenp0 int, basep uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getdents(C.int(fd), C.uintptr_t(_p0), C.size_t(_lenp0), C.uintptr_t(basep)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetgid() (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getgid())
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetpid() (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getpid())
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetpgid(pid int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getpgid(C.int(pid)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetpgrp() (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getpgrp())
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgeteuid() (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.geteuid())
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetegid() (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getegid())
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetppid() (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getppid())
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetpriority(which int, who int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getpriority(C.int(which), C.int(who)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetrlimit(which int, lim uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getrlimit(C.int(which), C.uintptr_t(lim)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetrusage(who int, rusage uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getrusage(C.int(who), C.uintptr_t(rusage)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgettimeofday(tv uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.gettimeofday(C.uintptr_t(tv)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetuid() (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getuid())
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callkill(pid int, signum int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.kill(C.int(pid), C.int(signum)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calllchown(_p0 uintptr, uid int, gid int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.lchown(C.uintptr_t(_p0), C.int(uid), C.int(gid)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calllink(_p0 uintptr, _p1 uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.link(C.uintptr_t(_p0), C.uintptr_t(_p1)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_llisten(s int, backlog int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.__xnet_llisten(C.int(s), C.int(backlog)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calllstat(_p0 uintptr, stat uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.lstat(C.uintptr_t(_p0), C.uintptr_t(stat)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmadvise(_p0 uintptr, _lenp0 int, advice int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.madvise(C.uintptr_t(_p0), C.size_t(_lenp0), C.int(advice)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmkdir(_p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.mkdir(C.uintptr_t(_p0), C.uint(mode)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmkdirat(dirfd int, _p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.mkdirat(C.int(dirfd), C.uintptr_t(_p0), C.uint(mode)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmkfifo(_p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.mkfifo(C.uintptr_t(_p0), C.uint(mode)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmkfifoat(dirfd int, _p0 uintptr, mode uint32) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.mkfifoat(C.int(dirfd), C.uintptr_t(_p0), C.uint(mode)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmknod(_p0 uintptr, mode uint32, dev int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.mknod(C.uintptr_t(_p0), C.uint(mode), C.int(dev)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmknodat(dirfd int, _p0 uintptr, mode uint32, dev int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.mknodat(C.int(dirfd), C.uintptr_t(_p0), C.uint(mode), C.int(dev)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmlock(_p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.mlock(C.uintptr_t(_p0), C.size_t(_lenp0)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmlockall(flags int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.mlockall(C.int(flags)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmprotect(_p0 uintptr, _lenp0 int, prot int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.mprotect(C.uintptr_t(_p0), C.size_t(_lenp0), C.int(prot)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmsync(_p0 uintptr, _lenp0 int, flags int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.msync(C.uintptr_t(_p0), C.size_t(_lenp0), C.int(flags)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmunlock(_p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.munlock(C.uintptr_t(_p0), C.size_t(_lenp0)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmunlockall() (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.munlockall())
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callnanosleep(time uintptr, leftover uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.nanosleep(C.uintptr_t(time), C.uintptr_t(leftover)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callopen(_p0 uintptr, mode int, perm uint32) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.open(C.uintptr_t(_p0), C.int(mode), C.uint(perm)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callopenat(dirfd int, _p0 uintptr, flags int, mode uint32) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.openat(C.int(dirfd), C.uintptr_t(_p0), C.int(flags), C.uint(mode)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callpathconf(_p0 uintptr, name int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.pathconf(C.uintptr_t(_p0), C.int(name)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callpause() (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.pause())
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callpread(fd int, _p0 uintptr, _lenp0 int, offset int64) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.pread(C.int(fd), C.uintptr_t(_p0), C.size_t(_lenp0), C.longlong(offset)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callpwrite(fd int, _p0 uintptr, _lenp0 int, offset int64) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.pwrite(C.int(fd), C.uintptr_t(_p0), C.size_t(_lenp0), C.longlong(offset)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callread(fd int, _p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.read(C.int(fd), C.uintptr_t(_p0), C.size_t(_lenp0)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callreadlink(_p0 uintptr, _p1 uintptr, _lenp1 int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.readlink(C.uintptr_t(_p0), C.uintptr_t(_p1), C.size_t(_lenp1)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callrename(_p0 uintptr, _p1 uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.rename(C.uintptr_t(_p0), C.uintptr_t(_p1)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callrenameat(olddirfd int, _p0 uintptr, newdirfd int, _p1 uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.renameat(C.int(olddirfd), C.uintptr_t(_p0), C.int(newdirfd), C.uintptr_t(_p1)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callrmdir(_p0 uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.rmdir(C.uintptr_t(_p0)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calllseek(fd int, offset int64, whence int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.lseek(C.int(fd), C.longlong(offset), C.int(whence)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callselect(nfd int, r uintptr, w uintptr, e uintptr, timeout uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.c_select(C.int(nfd), C.uintptr_t(r), C.uintptr_t(w), C.uintptr_t(e), C.uintptr_t(timeout)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetegid(egid int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.setegid(C.int(egid)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callseteuid(euid int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.seteuid(C.int(euid)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetgid(gid int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.setgid(C.int(gid)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsethostname(_p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.sethostname(C.uintptr_t(_p0), C.size_t(_lenp0)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetpgid(pid int, pgid int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.setpgid(C.int(pid), C.int(pgid)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetpriority(which int, who int, prio int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.setpriority(C.int(which), C.int(who), C.int(prio)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetregid(rgid int, egid int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.setregid(C.int(rgid), C.int(egid)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetreuid(ruid int, euid int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.setreuid(C.int(ruid), C.int(euid)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetrlimit(which int, lim uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.setrlimit(C.int(which), C.uintptr_t(lim)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetsid() (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.setsid())
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetuid(uid int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.setuid(C.int(uid)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callshutdown(s int, how int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.shutdown(C.int(s), C.int(how)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callstat(_p0 uintptr, stat uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.stat(C.uintptr_t(_p0), C.uintptr_t(stat)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callstatvfs(_p0 uintptr, vfsstat uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.statvfs(C.uintptr_t(_p0), C.uintptr_t(vfsstat)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsymlink(_p0 uintptr, _p1 uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.symlink(C.uintptr_t(_p0), C.uintptr_t(_p1)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsync() (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.sync())
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calltimes(tms uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.times(C.uintptr_t(tms)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calltruncate(_p0 uintptr, length int64) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.truncate(C.uintptr_t(_p0), C.longlong(length)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callfsync(fd int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.fsync(C.int(fd)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callftruncate(fd int, length int64) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.ftruncate(C.int(fd), C.longlong(length)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callumask(mask int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.umask(C.int(mask)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func calluname(buf uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.uname(C.uintptr_t(buf)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callumount(_p0 uintptr, flags int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.umount(C.uintptr_t(_p0), C.int(flags)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callunlink(_p0 uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.unlink(C.uintptr_t(_p0)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callunlinkat(dirfd int, _p0 uintptr, flags int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.unlinkat(C.int(dirfd), C.uintptr_t(_p0), C.int(flags)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callustat(dev int, ubuf uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.ustat(C.int(dev), C.uintptr_t(ubuf)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callutime(_p0 uintptr, buf uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.utime(C.uintptr_t(_p0), C.uintptr_t(buf)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_bind(s int, addr uintptr, addrlen uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.__xnet_bind(C.int(s), C.uintptr_t(addr), C.uintptr_t(addrlen)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_connect(s int, addr uintptr, addrlen uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.__xnet_connect(C.int(s), C.uintptr_t(addr), C.uintptr_t(addrlen)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmmap(addr uintptr, length uintptr, prot int, flag int, fd int, pos int64) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.mmap(C.uintptr_t(addr), C.uintptr_t(length), C.int(prot), C.int(flag), C.int(fd), C.longlong(pos)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callmunmap(addr uintptr, length uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.munmap(C.uintptr_t(addr), C.uintptr_t(length)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsendfile(outfd int, infd int, offset uintptr, count int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.sendfile(C.int(outfd), C.int(infd), C.uintptr_t(offset), C.int(count)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_sendto(s int, _p0 uintptr, _lenp0 int, flags int, to uintptr, addrlen uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.__xnet_sendto(C.int(s), C.uintptr_t(_p0), C.size_t(_lenp0), C.int(flags), C.uintptr_t(to), C.uintptr_t(addrlen)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_socket(domain int, typ int, proto int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.__xnet_socket(C.int(domain), C.int(typ), C.int(proto)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_socketpair(domain int, typ int, proto int, fd uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.__xnet_socketpair(C.int(domain), C.int(typ), C.int(proto), C.uintptr_t(fd)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callwrite(fd int, _p0 uintptr, _lenp0 int) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.write(C.int(fd), C.uintptr_t(_p0), C.size_t(_lenp0)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func call__xnet_getsockopt(s int, level int, name int, val uintptr, vallen uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.__xnet_getsockopt(C.int(s), C.int(level), C.int(name), C.uintptr_t(val), C.uintptr_t(vallen)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callgetpeername(fd int, rsa uintptr, addrlen uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.getpeername(C.int(fd), C.uintptr_t(rsa), C.uintptr_t(addrlen)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callsetsockopt(s int, level int, name int, val uintptr, vallen uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.setsockopt(C.int(s), C.int(level), C.int(name), C.uintptr_t(val), C.uintptr_t(vallen)))
	e1 = syscall.GetErrno()
	return
}
// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT

func callrecvfrom(fd int, _p0 uintptr, _lenp0 int, flags int, from uintptr, fromlen uintptr) (r1 uintptr, e1 Errno) {
	r1 = uintptr(C.recvfrom(C.int(fd), C.uintptr_t(_p0), C.size_t(_lenp0), C.int(flags), C.uintptr_t(from), C.uintptr_t(fromlen)))
	e1 = syscall.GetErrno()
	return
}

